// Code generated by counterfeiter. DO NOT EDIT.
package goauthhandlersfakes

import (
	sync "sync"

	goauth_handlers "github.com/SAP/goauth-handlers"
	token "github.com/SAP/goauth-handlers/token"
	oauth2 "golang.org/x/oauth2"
)

type FakeTokenDecoder struct {
	DecodeStub        func(*oauth2.Token) (token.Info, error)
	decodeMutex       sync.RWMutex
	decodeArgsForCall []struct {
		arg1 *oauth2.Token
	}
	decodeReturns struct {
		result1 token.Info
		result2 error
	}
	decodeReturnsOnCall map[int]struct {
		result1 token.Info
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenDecoder) Decode(arg1 *oauth2.Token) (token.Info, error) {
	fake.decodeMutex.Lock()
	ret, specificReturn := fake.decodeReturnsOnCall[len(fake.decodeArgsForCall)]
	fake.decodeArgsForCall = append(fake.decodeArgsForCall, struct {
		arg1 *oauth2.Token
	}{arg1})
	fake.recordInvocation("Decode", []interface{}{arg1})
	fake.decodeMutex.Unlock()
	if fake.DecodeStub != nil {
		return fake.DecodeStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.decodeReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokenDecoder) DecodeCallCount() int {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	return len(fake.decodeArgsForCall)
}

func (fake *FakeTokenDecoder) DecodeCalls(stub func(*oauth2.Token) (token.Info, error)) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = stub
}

func (fake *FakeTokenDecoder) DecodeArgsForCall(i int) *oauth2.Token {
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	argsForCall := fake.decodeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTokenDecoder) DecodeReturns(result1 token.Info, result2 error) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = nil
	fake.decodeReturns = struct {
		result1 token.Info
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDecoder) DecodeReturnsOnCall(i int, result1 token.Info, result2 error) {
	fake.decodeMutex.Lock()
	defer fake.decodeMutex.Unlock()
	fake.DecodeStub = nil
	if fake.decodeReturnsOnCall == nil {
		fake.decodeReturnsOnCall = make(map[int]struct {
			result1 token.Info
			result2 error
		})
	}
	fake.decodeReturnsOnCall[i] = struct {
		result1 token.Info
		result2 error
	}{result1, result2}
}

func (fake *FakeTokenDecoder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.decodeMutex.RLock()
	defer fake.decodeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenDecoder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ goauth_handlers.TokenDecoder = new(FakeTokenDecoder)
